/* eslint-disable */
// This file is auto-generated by Convex.
// Stub for build - will be replaced by `npx convex dev`

import type { AnyApi } from "convex/server";

export const api: any = {} as any;
export const internal: any = {} as any;
