/* eslint-disable */
// This file is auto-generated by Convex.
// Stub for build - will be replaced by `npx convex dev`

import type { AnyDataModel } from "convex/server";
export type DataModel = AnyDataModel;
